### ISSUE TITLE
Include filter step in SF to TW scenario

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-rest-tests#3]
Based on feedback from Keith pls include filter step that will be based on string with hashtag, e.g. `#salute` to cover common usage of hashtags on Twitter.

Example syndesis.yml:
```
---
flows:
- steps:
  - kind: endpoint
    uri: twitter-mention-connector--KvSUw7eYMcWe1kmZueI:MENTIONS
  - kind: filter
    expression: ${body.text} contains '#salute'
    steps:
    - kind: endpoint
      uri: atlas:mapping-step-3.json
    - kind: endpoint
      uri: salesforce-upsert-sobject--KvSV1v9YMcWe1kmZueJ?sObjectIdName=TwitterScreenName__c&sObjectName=Contact
```
